name: version-tag
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

permissions:
  contents: write

jobs:
  version-tag:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@a37ce9120846195fa4ece8f58b268e6043cb2f26 # v3
      - name: tag
        run: |
          git remote set-url origin "https://${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git"
          git tag "$(basename "${TAG%.*.*}")"
          git tag "$(basename "${TAG%.*}")"
          git push origin -f --tags
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          TAG: ${{ github.ref }}
